# Generated by Django 3.2.16 on 2023-03-19 14:02

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.AddField(
            model_name="profile",
            name="birthday",
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name="profile",
            name="coffee_count",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="cat-logo.png", upload_to=users.models.gen_user_path
            ),
        ),
    ]
