# Generated by Django 3.2.16 on 2023-03-22 19:46

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_profile_birthday"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxyUser",
            fields=[],
            options={
                "verbose_name": "прокси юзер",
                "verbose_name_plural": "прокси юзеры",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={
                "verbose_name": "профиль",
                "verbose_name_plural": "профили",
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.DateField(
                blank=True,
                default=None,
                null=True,
                verbose_name="дата рождения",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="coffee_count",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="сварено кофе"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="cat-logo.png",
                upload_to=users.models.gen_user_path,
                verbose_name="аватарка",
            ),
        ),
    ]
