# Generated by Django 3.2.16 on 2023-03-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedbackModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Сообщение")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Почта"),
                ),
            ],
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратные связи",
            },
        ),
    ]
