# Generated by Django 3.2.16 on 2023-03-14 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complainingusermodel",
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="feedbackmodel",
            options={
                "verbose_name": "обратная связь",
                "verbose_name_plural": "обратные связи",
            },
        ),
        migrations.CreateModel(
            name="FeedbackAttachments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="", verbose_name="Вложение"),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachment",
                        to="feedback.feedbackmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "вложение",
                "verbose_name_plural": "вложения",
            },
        ),
    ]
