# Generated by Django 3.2.16 on 2023-03-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_auto_20230314_2219"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackattachments",
            name="file",
            field=models.FileField(
                upload_to="attachments", verbose_name="Вложение"
            ),
        ),
    ]
