# Generated by Django 3.2.16 on 2023-03-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_feedbackmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Получено"),
                    ("processing", "В обработке"),
                    ("answered", "Ответ дан"),
                ],
                default="received",
                max_length=15,
            ),
        ),
    ]
