# Generated by Django 3.2.16 on 2023-03-14 20:13

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0003_alter_feedbackattachments_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackattachments",
            name="file",
            field=models.FileField(
                upload_to=feedback.models.attachment_handler,
                verbose_name="Вложение",
            ),
        ),
    ]
