# Generated by Django 3.2.16 on 2023-02-22 13:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import catalog.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Имя, содержит до 150 символов",
                        max_length=150,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Впишите slug-последовательность в поле",
                        max_length=200,
                        unique=True,
                        verbose_name="Слизняк",
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        default=100,
                        help_text="Вес - число от 0 до 32767",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(32767),
                        ],
                        verbose_name="Вес",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Имя, содержит до 150 символов",
                        max_length=150,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Впишите slug-последовательность в поле",
                        max_length=200,
                        unique=True,
                        verbose_name="Слизняк",
                    ),
                ),
            ],
            options={
                "verbose_name": "тэг",
                "verbose_name_plural": "тэги",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Имя, содержит до 150 символов",
                        max_length=150,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text='Текст должен содержать слово "превосходно" или "роскошно"',
                        validators=[
                            catalog.validators.GreatValidator(
                                "превосходно", "роскошно"
                            )
                        ],
                        verbose_name="Описание",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                    ),
                ),
                ("tags", models.ManyToManyField(to="catalog.Tag")),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
