# Generated by Django 3.2.16 on 2023-02-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="normalized",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="item",
            name="normalized",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="tag",
            name="normalized",
            field=models.TextField(default=""),
        ),
    ]
