# Generated by Django 3.2.16 on 2023-02-20 11:04

import catalog.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20230219_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogtag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='slug',
            field=models.TextField(help_text='Выберите категорию из списка', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Слизняк'),
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='weight',
            field=models.IntegerField(default=100, help_text='Вес - число от 0 до 32767', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32767)], verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='text',
            field=models.TextField(help_text='Текст должен содержать слово "превосходно" или "Роскошно"', validators=[catalog.models.great_validator], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='catalogtag',
            name='slug',
            field=models.TextField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Слизняк'),
        ),
    ]
