# Generated by Django 3.2.16 on 2023-02-22 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_auto_20230222_1648"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="normalized",
        ),
        migrations.RemoveField(
            model_name="item",
            name="normalized",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="normalized",
        ),
    ]
