# Generated by Django 3.2.16 on 2023-02-20 16:51

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_auto_20230220_1104"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogitem",
            name="text",
            field=models.TextField(
                help_text='Текст должен содержать слово "превосходно" или "роскошно"',
                validators=[catalog.models.great_validator],
                verbose_name="Описание",
            ),
        ),
    ]
