# Generated by Django 3.2.16 on 2023-02-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_auto_20230222_1653"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="normalized",
            field=models.TextField(default="", editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="item",
            name="normalized",
            field=models.TextField(default="", editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="normalized",
            field=models.TextField(default="", editable=False, unique=True),
        ),
    ]
