# Generated by Django 3.2.16 on 2023-02-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_auto_20230222_1703"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="main_image",
            field=models.ImageField(
                blank=True,
                default="static_dev/img/cat-logo.png",
                null=True,
                upload_to="titles/",
            ),
        ),
    ]
