# Generated by Django 3.2.16 on 2023-02-27 13:51

import catalog.validators
from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_gallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=models.ImageField(blank=True, default='../static_dev/img/cat-logo.png', null=True, upload_to='titles'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=django_quill.fields.QuillField(help_text='Текст должен содержать слово "превосходно" или "роскошно"', validators=[catalog.validators.GreatValidator('превосходно', 'роскошно')], verbose_name='Описание'),
        ),
    ]
