# Generated by Django 3.2.16 on 2023-02-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_alter_gallery_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(
                blank=True,
                default="../static_dev/img/cat-logo.png",
                null=True,
                upload_to="gallery",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="main_image",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.titleimage",
                verbose_name="иконка",
            ),
        ),
        migrations.AlterField(
            model_name="titleimage",
            name="image",
            field=models.ImageField(
                blank=True,
                default="../static_dev/img/cat-logo.png",
                null=True,
                upload_to="gallery",
                verbose_name="Изображение",
            ),
        ),
    ]
