# Generated by Django 3.2.16 on 2023-02-27 14:20

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20230227_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=django_quill.fields.QuillField(help_text='Текст должен содержать слово "превосходно" или "роскошно"', verbose_name='Описание'),
        ),
    ]
