# Generated by Django 3.2.16 on 2023-03-07 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_item_is_on_main"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("name",),
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.RemoveField(
            model_name="titleimage",
            name="image",
        ),
        migrations.AddField(
            model_name="titleimage",
            name="item",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.item",
                verbose_name="иконка",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="main_image",
            field=models.ImageField(
                default="../static_dev/img/cat-logo.png",
                upload_to="gallery",
                verbose_name="Основное изображение",
            ),
        ),
    ]
