# Generated by Django 3.2.16 on 2023-03-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_auto_20230307_0800"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(
                default="../static_dev/img/cat-logo.png",
                upload_to="gallery",
                verbose_name="Изображение",
            ),
        ),
    ]
