# Generated by Django 3.2.16 on 2023-03-07 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0015_item_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="main_image",
        ),
    ]
