# Generated by Django 3.2.16 on 2023-03-07 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0016_remove_item_main_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={
                "verbose_name": "дополнительное фото",
                "verbose_name_plural": "дополнительные фото",
            },
        ),
        migrations.AlterField(
            model_name="gallery",
            name="item",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery",
                to="catalog.item",
            ),
        ),
        migrations.AlterField(
            model_name="titleimage",
            name="item",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="title_image",
                to="catalog.item",
                verbose_name="иконка",
            ),
        ),
    ]
