# Generated by Django 3.2.16 on 2023-03-08 18:23

import catalog.validators
from django.db import migrations, models
import django.utils.timezone
import django_quill.fields


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0017_auto_20230307_2314"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="время изменения"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="date_published",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="время публикации",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=django_quill.fields.QuillField(
                help_text='Текст должен содержать слово "превосходно" или "роскошно"',
                validators=[
                    catalog.validators.GreatValidator(
                        "роскошно", "превосходно"
                    )
                ],
                verbose_name="Описание",
            ),
        ),
    ]
