# Generated by Django 3.2.16 on 2023-03-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0018_auto_20230308_2123"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(
                default="cat-logo.png",
                upload_to="gallery",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                default="cat-logo.png",
                upload_to="gallery",
                verbose_name="Изображение",
            ),
        ),
    ]
