# Generated by Django 3.2.16 on 2023-03-13 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0020_alter_titleimage_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="image",
        ),
        migrations.RemoveField(
            model_name="titleimage",
            name="item",
        ),
        migrations.AddField(
            model_name="titleimage",
            name="image",
            field=models.ImageField(
                default="cat-logo.png",
                upload_to="gallery",
                verbose_name="Изображение",
            ),
        ),
        migrations.AddField(
            model_name="titleimage",
            name="title_image",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="title_image",
                to="catalog.item",
                verbose_name="иконка",
            ),
        ),
    ]
