# Generated by Django 3.2.16 on 2023-03-13 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0021_auto_20230313_1223"),
    ]

    operations = [
        migrations.RenameField(
            model_name="titleimage",
            old_name="title_image",
            new_name="item",
        ),
    ]
