# Generated by Django 3.2.16 on 2023-03-13 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0022_rename_title_image_titleimage_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titleimage",
            name="item",
            field=models.OneToOneField(
                default="cat-logo.png",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="title_image",
                to="catalog.item",
                verbose_name="иконка",
            ),
        ),
    ]
